/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as CreativeAssistanceRouteImport } from './routes/creative-assistance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductionsIndexRouteImport } from './routes/productions.index'
import { Route as ProductionsSlugRouteImport } from './routes/productions.$slug'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeAssistanceRoute = CreativeAssistanceRouteImport.update({
  id: '/creative-assistance',
  path: '/creative-assistance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionsIndexRoute = ProductionsIndexRouteImport.update({
  id: '/productions/',
  path: '/productions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionsSlugRoute = ProductionsSlugRouteImport.update({
  id: '/productions/$slug',
  path: '/productions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/creative-assistance': typeof CreativeAssistanceRoute
  '/projects': typeof ProjectsRoute
  '/productions/$slug': typeof ProductionsSlugRoute
  '/productions/': typeof ProductionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/creative-assistance': typeof CreativeAssistanceRoute
  '/projects': typeof ProjectsRoute
  '/productions/$slug': typeof ProductionsSlugRoute
  '/productions': typeof ProductionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/creative-assistance': typeof CreativeAssistanceRoute
  '/projects': typeof ProjectsRoute
  '/productions/$slug': typeof ProductionsSlugRoute
  '/productions/': typeof ProductionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/creative-assistance'
    | '/projects'
    | '/productions/$slug'
    | '/productions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/creative-assistance'
    | '/projects'
    | '/productions/$slug'
    | '/productions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/creative-assistance'
    | '/projects'
    | '/productions/$slug'
    | '/productions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CreativeAssistanceRoute: typeof CreativeAssistanceRoute
  ProjectsRoute: typeof ProjectsRoute
  ProductionsSlugRoute: typeof ProductionsSlugRoute
  ProductionsIndexRoute: typeof ProductionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative-assistance': {
      id: '/creative-assistance'
      path: '/creative-assistance'
      fullPath: '/creative-assistance'
      preLoaderRoute: typeof CreativeAssistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productions/': {
      id: '/productions/'
      path: '/productions'
      fullPath: '/productions/'
      preLoaderRoute: typeof ProductionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productions/$slug': {
      id: '/productions/$slug'
      path: '/productions/$slug'
      fullPath: '/productions/$slug'
      preLoaderRoute: typeof ProductionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CreativeAssistanceRoute: CreativeAssistanceRoute,
  ProjectsRoute: ProjectsRoute,
  ProductionsSlugRoute: ProductionsSlugRoute,
  ProductionsIndexRoute: ProductionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
